### ISSUE TITLE
Launching RenderBender from the Windows Start menu doesn't load the options

### ISSUE THREAD

**Issue by ABUCKY0** [SpeedyCodes/RenderBender#3]

**Comment by SpeedyCodes** [comment]
Did you add a RenderBender shortcut to the Start Menu manually? I'm not sure what the problem could be there, but I'm currently planning to release a proper installer executable with every release starting from v0.3.1. I will, of course, make sure the preferences are loaded properly after installing RenderBender that way.

**Comment by ABUCKY0** [comment]
I press on the windows button, and then search for RenderBender, and it launches renderblender with no options

**Comment by SpeedyCodes** [comment]
Oh, that's odd. Do you mean options as in Preferences, or do you mean settings for Minecraft?

**Comment by ABUCKY0** [comment]
No like the different things you can change with renderblender don’t show up. It’s like when starting it from the start menu it doesn’t load the options or settings file

**Comment by SpeedyCodes** [comment]
Are you sure that the RenderBender executable that is opened via the search bar is the correct one? Version 0.3.0?

**Comment by ABUCKY0** [comment]
The only version I’ve ever downloaded so yes I am sure

**Comment by SpeedyCodes** [comment]
This has been fixed in the 0.3.1 release. Thank you for reporting this issue!
