### ISSUE TITLE
RenderBender v0.3.1 Will start minecraft, but won't start itself.

### ISSUE THREAD

**Issue by ABUCKY0** [SpeedyCodes/RenderBender#5]
Me and ValikLetsPlay can't get renderbender to start properly, using the installer, or the zip file.

**Comment by Rayth** [comment]
I also cant get render bender to start when minecraft is already open either.

**Comment by ABUCKY0** [comment]
Yeah me and Speedy are working on it, it's just hard because of the like 10 hour time difference.

**Comment by SpeedyCodes** [comment]
This has finally been solved! The v0.3.1 release was edited with a fixed .zip and installer .exe.
